
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
    
services:
  idrac-sse:
    container_name: idrac-sse
    build:
      context: ./src/idrac-sse
    restart: unless-stopped
    environment:
      - LOGLEVEL=INFO
      - TZINFO=America/Denver
      - iDRAC_USERNAME=root
      - iDRAC_PASSWORD
      - iDRAC_SSE_OTEL_RECEIVER=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}
      - iDRAC_SSE_HTTP_RECEIVER
      - iDRAC_SSE_HOSTNAME_VALUE_FROM
      - iDRAC_SSE_STOMP_SERVER
      - iDRAC_SSE_STOMP_PORT
      - iDRAC_SSE_STOMP_USER
      - iDRAC_SSE_STOMP_PASS
      - iDRAC_SSE_TOPIC_LOG
      - iDRAC_SSE_TOPIC_METRIC
      - iDRAC_SSE_TOPIC_STAT
    volumes:
      #- ./hosts_test:/code/app/hosts
      - ./hosts:/code/app/hosts
    depends_on:
      activemq:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - idrac-sse-demo

  # Generate SSL Certificate: openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365
  idrac-sse-testserver:
    container_name: idrac-sse-testserver
    build:
      context: ./src/test-server
    restart: unless-stopped
    ports:
      - 8443:443
    networks:
      - idrac-sse-demo
    volumes:
      - /tmp/reports:/code/app/example_metrics

  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml" ]
    user: 0:0
    volumes:
      - ${HOST_FILESYSTEM}:/hostfs:ro
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - ${OTEL_COLLECTOR_CONFIG}:/etc/otelcol-config.yml
    ports:
      - "${OTEL_COLLECTOR_PORT_GRPC}"
      - "${OTEL_COLLECTOR_PORT_HTTP}:${OTEL_COLLECTOR_PORT_HTTP}"
    logging: *logging
    environment:
      - ENVOY_PORT
      - HOST_FILESYSTEM
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
      - OTEL_COLLECTOR_PORT_HTTP
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
    networks:
      - idrac-sse-demo

  activemq:
    container_name: activemq
    image: rmohr/activemq:latest
    environment:
      ACTIVEMQ_WEBADMIN_USERNAME: admin
      ACTIVEMQ_WEBADMIN_PASSWORD: admin
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "61616:61616"  # OpenWire port
      - "61613:61613"  # STOMP port
      - "8161:8161"    # WebConsole port
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f http://localhost:8161"]
      interval: 5s
    networks:
      - idrac-sse-demo

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=24h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --web.enable-otlp-receiver
      #- --enable-feature=exemplar-storage
    volumes:
      - ./src/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "9090:9090"
    logging: *logging
    networks:
      - idrac-sse-demo

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./src/loki/local-config.yaml:/etc/loki/local-config.yaml
    networks:
      - idrac-sse-demo

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 120M
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=grafana-opensearch-datasource"
    volumes:
      - ./src/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./src/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    logging: *logging
    networks:
      - idrac-sse-demo

networks:
  idrac-sse-demo:
    driver: bridge