

services:
  idrac-sse:
    container_name: idrac-sse
    build:
      context: ./src/idrac-sse
    restart: unless-stopped
    environment:
      - "iDRAC_USERNAME=root"
      - iDRAC_PASSWORD
      - OTEL_RECEIVER
      - HTTP_RECEIVER
    volumes:
      - ./hosts:/code/app/hosts
    #network_mode: host
    networks:
      - idrac-sse-demo

  # Generate SSL Certificate: openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365
  idrac-sse-testserver:
    container_name: idrac-sse-testserver
    build:
      context: ./src/test-server
    restart: unless-stopped
    command: "uvicorn app.server:app --reload --host 0.0.0.0 --port 443 --ssl-keyfile /code/app/key.pem --ssl-certfile /code/app/cert.pem"
    ports:
      - 8000:8000
    networks:
      - idrac-sse-demo

networks:
  idrac-sse-demo:
    driver: bridge