---
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  #max_transfer_retries: 0
  wal:
    dir: /loki/wal

schema_config:
  configs:
    - from: "2023-01-05" # <---- A date in the future
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v13
      store: tsdb

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/data/tsdb-index
    cache_location: /loki/data/tsdb-cache

  filesystem:
    directory: /loki/data

compactor:
  working_directory: /loki/retention
  #retention_enabled: true

limits_config:
  #enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: true # Required for OTEL Collector

chunk_store_config:
  #max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s